package com.unitbv.myquizapi.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Response object containing the content generated by the AI, the model used, and the timestamp of generation.")
public class OllamaGenerateResponseDto {

    @Schema(
            description = "The content generated by the AI model.",
            example = "1. Who was the first ruler of Romania?\n2. When did Romania become a kingdom?\n3. Name a famous Romanian historian."
    )
    private String response;

    @Schema(
            description = "The AI model used for generating the response.",
            example = "llama3"
    )
    private String model;

    @Schema(
            description = "The date and time when the response was generated.",
            example = "2025-12-07T21:30:00+02:00"
    )
    private OffsetDateTime timestamp;
}
