# Docker-specific Spring Boot configuration
spring:
  # Database configuration for Docker container
  datasource:
    url: jdbc:postgresql://postgres:5432/myquiz
    username: ${SPRING_DATASOURCE_USERNAME:myquiz_user}
    password: ${SPRING_DATASOURCE_PASSWORD:myquiz_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # Thymeleaf configuration
  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Logging configuration
logging:
  level:
    com.unitbv.myquiz: INFO
    org.springframework: WARN
    org.hibernate: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/myquiz-app.log
    max-size: 10MB
    max-history: 10

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /api/system
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Application-specific configuration
myquiz:
  upload:
    directory: /app/uploads
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      enabled: ${AI_ENABLED:false}
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
